// LanguageContext.js
import { createContext, useContext, useState } from 'react';

const translations = {
  en: {
    translateLanguageTitle: 'Translate Language',
    selectedLanguage: 'Selected Language:',
    enterTextPlaceholder: 'Enter text to translate',
    translatedText: 'Translated Text',
    translateButton: 'Translate',
    selectLang: 'Select Language',
    selectTargetLang: 'Select target Language',
    matchingGameTitle: 'Matching Game',
    exitTitle: 'Exit',
    wordBookTitle: 'Word Book',
    translationTitle: 'Translation',
    commonPhrasesTitle: 'Common Phrases',
    congratulationTitle: 'Congratulations!',
    congratulationTitle2: 'You matched all pairs!',
    okTitle: 'Ok',
    travelPhrasesTitle: 'Travel Phrases',
    emergencyPhrasesTitle: 'Emergency Phrases',
  },
  ar: {
    translateLanguageTitle: 'ترجمة اللغة',
    selectedLanguage: 'اللغة المختارة:',
    enterTextPlaceholder: 'أدخل النص للترجمة',
    translatedText: 'النص المترجم',
    translateButton: 'ترجمة',
    selectLang: 'اختر اللغة',
    selectTargetLang: 'اختر اللغة المستهدفة',
    matchingGameTitle: 'لعبة المطابقة',
    exitTitle: 'خروج',
    wordBookTitle: 'كتاب الكلمات',
    translationTitle: 'الترجمة',
    commonPhrasesTitle: 'عبارة شائعة',
    congratulationTitle: 'تهانينا!',
    congratulationTitle2: 'لقد تم مطابقة جميع الأزواج!',
    okTitle: 'حسنا',
    travelPhrasesTitle: 'عبارات السفر',
    emergencyPhrasesTitle: 'عبارات الطوارئ',
  },
  bn: {
    translateLanguageTitle: 'ভাষা অনুবাদ করুন',
    selectedLanguage: 'নির্বাচিত ভাষা:',
    enterTextPlaceholder: 'অনুবাদ করার জন্য টেক্সট লিখুন',
    translatedText: 'অনুবাদিত টেক্সট',
    translateButton: 'অনুবাদ',
    selectLang: 'ভাষা নির্বাচন করুন',
    selectTargetLang: 'লক্ষিত ভাষা নির্বাচন করুন',
    matchingGameTitle: 'ম্যাচিং গেম',
    exitTitle: 'প্রস্থান',
    wordBookTitle: 'শব্দ বই',
    translationTitle: 'অনুবাদ',
    commonPhrasesTitle: 'সাধারিত বাক্য',
    congratulationTitle: 'অভিনন্দন!',
    congratulationTitle2: 'আপনি সমস্ত জোড়া মেলালেন!',
    okTitle: 'ঠিক আছে',
    travelPhrasesTitle: 'ভ্রমণ বাক্য',
    emergencyPhrasesTitle: 'জরুরি বাক্য',
  },
  nl: {
    translateLanguageTitle: 'Taal vertalen',
    selectedLanguage: 'Geselecteerde taal:',
    enterTextPlaceholder: 'Voer tekst in om te vertalen',
    translatedText: 'Vertaalde tekst',
    translateButton: 'Vertalen',
    selectLang: 'Selecteer taal',
    selectTargetLang: 'Selecteer doeltaal',
    matchingGameTitle: 'bijpassend spel',
    exitTitle: 'Afsluiten',
    wordBookTitle: 'Woordenboek',
    translationTitle: 'Vertaling',
    commonPhrasesTitle: 'Gemeenschappelijke Uitdrukking',
    congratulationTitle: 'Gefeliciteerd!',
    congratulationTitle2: 'Je hebt alle paren gevonden!',
    okTitle: 'Oké',
    travelPhrasesTitle: 'Reisuitdrukking',
    emergencyPhrasesTitle: 'Nooduitdrukking',
  },
  fr: {
    translateLanguageTitle: 'Traduire la langue',
    selectedLanguage: 'Langue sélectionnée:',
    enterTextPlaceholder: 'Saisissez le texte à traduire',
    translatedText: 'Texte traduit',
    translateButton: 'Traduire',
    selectLang: 'Sélectionner la langue',
    selectTargetLang: 'Sélectionner la langue cible',
    matchingGameTitle: 'Jeu de correspondance',
    exitTitle: 'Quitter',
    wordBookTitle: 'Livre de mots',
    translationTitle: 'Traduction',
    commonPhrasesTitle: 'Expression Courante',
    congratulationTitle: 'Félicitations!',
    congratulationTitle2: 'Vous avez assorti toutes les paires!',
    okTitle: 'D\'accord',
    travelPhrasesTitle: 'Phrase de voyage',
    emergencyPhrasesTitle: 'Phrase d\'urgence',
  },
  de: {
    translateLanguageTitle: 'Sprache übersetzen',
    selectedLanguage: 'Ausgewählte Sprache:',
    enterTextPlaceholder: 'Geben Sie den zu übersetzenden Text ein',
    translatedText: 'Übersetzter Text',
    translateButton: 'Übersetzen',
    selectLang: 'Sprache auswählen',
    selectTargetLang: 'Zielsprache auswählen',
    matchingGameTitle: 'Matching-Spiel',
    exitTitle: 'Beenden',
    wordBookTitle: 'Wörterbuch',
    translationTitle: 'Übersetzung',
    commonPhrasesTitle: 'Gemeinsamer Ausdruck',
    congratulationTitle: 'Herzlichen Glückwunsch!',
    congratulationTitle2: 'Du hast alle Paare gefunden!',
    okTitle: 'Ok',
    travelPhrasesTitle: 'Reisesatz',
    emergencyPhrasesTitle: 'Notfallsatz',
  },
  hi: {
    translateLanguageTitle: 'भाषा अनुवाद करें',
    selectedLanguage: 'चयनित भाषा:',
    enterTextPlaceholder: 'अनुवाद के लिए पाठ दर्ज करें',
    translatedText: 'अनुवादित पाठ',
    translateButton: 'अनुवाद करें',
    selectLang: 'भाषा चुनें',
    selectTargetLang: 'लक्षित भाषा चुनें',
    matchingGameTitle: 'मैचिंग गेम',
    exitTitle: 'बाहर जाएं',
    wordBookTitle: 'शब्दपुस्तक',
    translationTitle: 'अनुवाद',
    commonPhrasesTitle: 'सामान्य वाक्य',
    congratulationTitle: 'बधाई हो!',
    congratulationTitle2: 'आपने सभी जोड़ीयाँ मिलाई हैं!',
    okTitle: 'ठीक है',
    travelPhrasesTitle: 'यात्रा वाक्य',
    emergencyPhrasesTitle: 'आपातकालीन वाक्य',
  },
  it: {
    translateLanguageTitle: 'Traduci lingua',
    selectedLanguage: 'Lingua selezionata:',
    enterTextPlaceholder: 'Inserisci il testo da tradurre',
    translatedText: 'Testo tradotto',
    translateButton: 'Traduci',
    selectLang: 'Seleziona lingua',
    selectTargetLang: 'Seleziona lingua di destinazione',
    matchingGameTitle: 'Gioco abbinato',
    exitTitle: 'Esci',
    wordBookTitle: 'Libro delle parole',
    translationTitle: 'Traduzione',
    commonPhrasesTitle: 'Frase Comune',
    congratulationTitle: 'Congratulazioni!',
    congratulationTitle2: 'Hai abbinato tutte le coppie!',
    okTitle: 'Ok',
    travelPhrasesTitle: 'Frase di viaggio',
    emergencyPhrasesTitle: 'Frase di emergenza',
  },
  id: {
    translateLanguageTitle: 'Terjemahkan Bahasa',
    selectedLanguage: 'Bahasa yang Dipilih:',
    enterTextPlaceholder: 'Masukkan teks untuk diterjemahkan',
    translatedText: 'Teks yang Diterjemahkan',
    translateButton: 'Terjemahkan',
    selectLang: 'Pilih Bahasa',
    selectTargetLang: 'Pilih Bahasa Tujuan',
    matchingGameTitle: 'Permainan Pencocokan',
    exitTitle: 'Keluar',
    wordBookTitle: 'Buku Kata',
    translationTitle: 'Terjemahan',
    commonPhrasesTitle: 'Frase Umum',
    congratulationTitle: 'Selamat!',
    congratulationTitle2: 'Anda mencocokkan semua pasangan!',
    okTitle: 'Oke',
    travelPhrasesTitle: 'Frase Perjalanan',
    emergencyPhrasesTitle: 'Frase Darurat',
  },
  ja: {
    translateLanguageTitle: '言語を翻訳する',
    selectedLanguage: '選択した言語:',
    enterTextPlaceholder: '翻訳するテキストを入力してください',
    translatedText: '翻訳されたテキスト',
    translateButton: '翻訳',
    selectLang: '言語を選択',
    selectTargetLang: '目標言語を選択',
    matchingGameTitle: 'マッチングゲーム',
    exitTitle: '終了',
    wordBookTitle: '単語帳',
    translationTitle: '翻訳',
    commonPhrasesTitle: '共通フレーズ',
    congratulationTitle: 'おめでとうございます！',
    congratulationTitle2: 'すべてのペアが一致しました！',
    okTitle: 'はい',
    travelPhrasesTitle: '旅行フレーズ',
    emergencyPhrasesTitle: '緊急フレーズ',
  },
  ko: {
    translateLanguageTitle: '언어 번역',
    selectedLanguage: '선택한 언어:',
    enterTextPlaceholder: '번역할 텍스트를 입력하세요',
    translatedText: '번역된 텍스트',
    translateButton: '번역',
    selectLang: '언어 선택',
    selectTargetLang: '대상 언어 선택',
    matchingGameTitle: '매칭 게임',
    exitTitle: '종료',
    wordBookTitle: '단어장',
    translationTitle: '번역',
    commonPhrasesTitle: '일반구문',
    congratulationTitle: '축하합니다!',
    congratulationTitle2: '모든 쌍을 맞추셨습니다!',
    okTitle: '확인',
    travelPhrasesTitle: '여행 표현',
    emergencyPhrasesTitle: '긴급 표현',
  },
  ml: {
    translateLanguageTitle: 'ഭാഷ അനുവദിക്കുക',
    selectedLanguage: 'തിരഞ്ഞെടുത്ത ഭാഷ:',
    enterTextPlaceholder: 'അനുവദിക്കാൻ ടെക്സ്റ്റ് നൽകുക',
    translatedText: 'അനുവദിച്ച ടെക്സ്റ്റ്',
    translateButton: 'അനുവദിക്കുക',
    selectLang: 'ഭാഷ തിരഞ്ഞെടുക്കുക',
    selectTargetLang: 'ലക്ഷിത ഭാഷ തിരഞ്ഞെടുക്കുക',
    matchingGameTitle: 'സരിചെയ്തു പഠിക്കുക',
    exitTitle: 'പുറത്തുപോകുക',
    wordBookTitle: 'വാർഡ് ബുക്ക്',
    translationTitle: 'അനുവാദം',
    commonPhrasesTitle: 'സാമാന്യ വാക്യം',
    congratulationTitle: 'അഭിനന്ദനങ്ങൾ!',
    congratulationTitle2: 'നിന്നെയും എല്ലാ ജോഡുകളും മാച്ചു!',
    okTitle: 'ശരി',
    travelPhrasesTitle: 'യാത്ര വാക്കുകൾ',
    emergencyPhrasesTitle: 'അതിരിലെ വാക്കുകൾ',
  },
  zh: {
    translateLanguageTitle: '翻译语言',
    selectedLanguage: '选择的语言:',
    enterTextPlaceholder: '输入要翻译的文本',
    translatedText: '翻译文本',
    translateButton: '翻译',
    selectLang: '选择语言',
    selectTargetLang: '选择目标语言',
    matchingGameTitle: '匹配游戏',
    exitTitle: '退出',
    wordBookTitle: '词汇书',
    translationTitle: '翻译',
    commonPhrasesTitle: '常用短语',
    congratulationTitle: '恭喜！',
    congratulationTitle2: '您已匹配所有配对！',
    okTitle: '好的',
    travelPhrasesTitle: '旅行短语',
    emergencyPhrasesTitle: '紧急短语',
  },
  mr: {
    translateLanguageTitle: 'भाषा अनुवाद करा',
    selectedLanguage: 'निवडलेली भाषा:',
    enterTextPlaceholder: 'अनुवाद करण्यासाठी टेक्स्ट प्रविष्ट करा',
    translatedText: 'अनुवादित टेक्स्ट',
    translateButton: 'भाषा अनुवादित करा',
    selectLang: 'भाषा निवडा',
    selectTargetLang: 'लक्षित भाषा निवडा',
    matchingGameTitle: 'मॅचिंग गेम',
    exitTitle: 'बाहेर पडा',
    wordBookTitle: 'शब्दपुस्तक',
    translationTitle: 'भाषांतर',
    commonPhrasesTitle: 'सामान्य वाक्य',
    congratulationTitle: 'अभिनंदन!',
    congratulationTitle2: 'तुम्ही सर्व जोडींची मॅच केली!',
    okTitle: 'ठीक आहे',
    travelPhrasesTitle: 'प्रवास वाक्य',
    emergencyPhrasesTitle: 'आपत्कालीन वाक्य',
  },
  fa: {
    translateLanguageTitle: 'ترجمه زبان',
    selectedLanguage: 'زبان انتخاب شده:',
    enterTextPlaceholder: 'متن را برای ترجمه وارد کنید',
    translatedText: 'متن ترجمه شده',
    translateButton: 'ترجمه',
    selectLang: 'زبان را انتخاب کنید',
    selectTargetLang: 'زبان هدف را انتخاب کنید',
    matchingGameTitle: 'بازی تطبیق',
    exitTitle: 'خروج',
    wordBookTitle: 'کتاب کلمات',
    translationTitle: 'ترجمه',
    commonPhrasesTitle: 'عبارت متداول',
    congratulationTitle: 'تبریک!',
    congratulationTitle2: 'شما همه جفت ها را متناسب ساخته اید!',
    okTitle: 'خب',
    travelPhrasesTitle: 'عبارات مسافرت',
    emergencyPhrasesTitle: 'عبارات اضطراری',
  },
  pl: {
    translateLanguageTitle: 'Tłumacz język',
    selectedLanguage: 'Wybrany język:',
    enterTextPlaceholder: 'Wprowadź tekst do tłumaczenia',
    translatedText: 'Przetłumaczony tekst',
    translateButton: 'Tłumacz',
    selectLang: 'Wybierz język',
    selectTargetLang: 'Wybierz język docelowy',
    matchingGameTitle: 'Gra dopasowująca',
    exitTitle: 'Wyjście',
    wordBookTitle: 'Słownik',
    translationTitle: 'Tłumaczenie',
    commonPhrasesTitle: 'Wspólna Fraza',
    congratulationTitle: 'Gratulacje!',
    congratulationTitle2: 'Udało ci się dopasować wszystkie pary!',
    okTitle: 'Ok',
    travelPhrasesTitle: 'Zdanie podróży',
    emergencyPhrasesTitle: 'Zdanie awaryjne',
  },
  pt: {
    translateLanguageTitle: 'Traduzir idioma',
    selectedLanguage: 'Idioma selecionado:',
    enterTextPlaceholder: 'Digite o texto para traduzir',
    translatedText: 'Texto traduzido',
    translateButton: 'Traduzir',
    selectLang: 'Selecionar Idioma',
    selectTargetLang: 'Selecionar Idioma Alvo',
    matchingGameTitle: 'Jogo de correspondência',
    exitTitle: 'Sair',
    wordBookTitle: 'Livro de palavras',
    translationTitle: 'Tradução',
    commonPhrasesTitle: 'Frase Comum',
    congratulationTitle: 'Parabéns!',
    congratulationTitle2: 'Você combinou todos os pares!',
    okTitle: 'Ok',
    travelPhrasesTitle: 'Frase de viagem',
    emergencyPhrasesTitle: 'Frase de emergência',
  },
  pa: {
    translateLanguageTitle: 'ਭਾਸ਼ਾ ਅਨੁਵਾਦ ਕਰੋ',
    selectedLanguage: 'ਚੁਣੀ ਭਾਸ਼ਾ:',
    enterTextPlaceholder: 'ਅਨੁਵਾਦ ਕਰਨ ਲਈ ਟੈਕਸਟ ਦਾਖਲ ਕਰੋ',
    translatedText: 'ਅਨੁਵਾਦਿਤ ਟੈਕਸਟ',
    translateButton: 'ਅਨੁਵਾਦ ਕਰੋ',
    selectLang: 'ਭਾਸ਼ਾ ਚੁਣੋ',
    selectTargetLang: 'ਲਕੜੀ ਭਾਸ਼ਾ ਚੁਣੋ',
    matchingGameTitle: 'ਮੈਚਿੰਗ ਗੇਮ',
    exitTitle: 'ਬਾਹਰ ਜਾਓ',
    wordBookTitle: 'ਸ਼ਬਦ ਪੁਸਤਕ',
    translationTitle: 'ਅਨੁਵਾਦ',
    commonPhrasesTitle: 'ਆਮ ਤਾਜਗੀ',
    congratulationTitle: 'ਵਧਾਈਆਂ!',
    congratulationTitle2: 'ਤੁਸੀਂ ਸਾਰੇ ਜੋੜੇ ਮੈਚ ਕੀਤੇ ਹਨ!',
    okTitle: 'ਠੀਕ ਹੈ',
    travelPhrasesTitle: 'ਯਾਤਰਾ ਵਾਕ',
    emergencyPhrasesTitle: 'ਆਤਾਤਰ ਵਾਕ',
  },
  ru: {
    translateLanguageTitle: 'Перевести язык',
    selectedLanguage: 'Выбранный язык:',
    enterTextPlaceholder: 'Введите текст для перевода',
    translatedText: 'Переведенный текст',
    translateButton: 'Перевести',
    selectLang: 'Выберите язык',
    selectTargetLang: 'Выберите целевой язык',
    matchingGameTitle: 'Игра в сопоставление',
    exitTitle: 'Выход',
    wordBookTitle: 'Словарь',
    translationTitle: 'Перевод',
    commonPhrasesTitle: 'Общее Выражение',
    congratulationTitle: 'Поздравляю!',
    congratulationTitle2: 'Вы совпали со всеми парами!',
    okTitle: 'Хорошо',
    travelPhrasesTitle: 'Фраза для путешествия',
    emergencyPhrasesTitle: 'Фраза для чрезвычайной ситуации',
  },
  es: {
    translateLanguageTitle: 'Traducir idioma',
    selectedLanguage: 'Idioma seleccionado:',
    enterTextPlaceholder: 'Ingrese texto para traducir',
    translatedText: 'Texto traducido',
    translateButton: 'Traducir',
    selectLang: 'Seleccionar idioma',
    selectTargetLang: 'Seleccionar idioma de destino',
    matchingGameTitle: 'Juego de coincidencias',
    exitTitle: 'Salir',
    wordBookTitle: 'Libro de palabras',
    translationTitle: 'Traducción',
    commonPhrasesTitle: 'Frase Común',
    congratulationTitle: '¡Felicidades!',
    congratulationTitle2: 'Has emparejado todas las parejas!',
    okTitle: 'Ok',
    travelPhrasesTitle: 'Frase de viaje',
    emergencyPhrasesTitle: 'Frase de emergencia',
  },
  sw: {
    translateLanguageTitle: 'Tafsiri Lugha',
    selectedLanguage: 'Lugha iliyochaguliwa:',
    enterTextPlaceholder: 'Ingiza maandishi ya kutafsiri',
    translatedText: 'Maandishi yaliyotafsiriwa',
    translateButton: 'Tafsiri',
    selectLang: 'Chagua Lugha',
    selectTargetLang: 'Chagua Lugha ya Lengo',
    matchingGameTitle: 'Mchezo wa Kupatanisha',
    exitTitle: 'Kutokea',
    wordBookTitle: 'Kitabu cha Neno',
    translationTitle: 'Tafsiri',
    commonPhrasesTitle: 'Neno la Kawaida',
    congratulationTitle: 'Hongera!',
    congratulationTitle2: 'Umepatana na jozi zote!',
    okTitle: 'Sawa',
    travelPhrasesTitle: 'Sensa ya Safari',
    emergencyPhrasesTitle: 'Sensa ya Dharura',
  },
  tl: {
    translateLanguageTitle: 'Isalin ang Wika',
    selectedLanguage: 'Piniling Wika:',
    enterTextPlaceholder: 'Ilagay ang teksto na nais isalin',
    translatedText: 'Isinalin na Teksto',
    translateButton: 'Isalin',
    selectLang: 'Pumili ng Wika',
    selectTargetLang: 'Pumili ng Layunin na Wika',
    matchingGameTitle: 'pagtutugma ng laro',
    exitTitle: 'Lumabas',
    wordBookTitle: 'Aklat ng Salita',
    translationTitle: 'Pagsasalin',
    commonPhrasesTitle: 'Karaniwang Parirala',
    congratulationTitle: 'Congratulations!',
    congratulationTitle2: 'Nakapares mo ang lahat ng mga pares!',
    okTitle: 'Sige',
    travelPhrasesTitle: 'Wika ng Paglalakbay',
    emergencyPhrasesTitle: 'Wika ng Emergency',
  },
  ta: {
    translateLanguageTitle: 'மொழியை மொழிபெயர்க்கவும்',
    selectedLanguage: 'தேர்ந்தெடுக்கப்பட்ட மொழி:',
    enterTextPlaceholder: 'மொழிபெயர்க்க உரை உள்ளிடவும்',
    translatedText: 'மொழிபெயர்க்கப்பட்ட உரை',
    translateButton: 'மொழிபெயர்க்கவும்',
    selectLang: 'மொழியை தேர்ந்தெடு',
    selectTargetLang: 'லக்ஷித மொழியை தேர்ந்தெடு',
    matchingGameTitle: 'பொருத்தம் விளையாட்டு',
    exitTitle: 'வெளியேறு',
    wordBookTitle: 'சொல் புத்தகம்',
    translationTitle: 'மொழிபெயர்ப்பு',
    commonPhrasesTitle: 'பொது வாக்குத்தத்தம்',
    travelPhrasesTitle: 'பயண வாக்குகள்',
    emergencyPhrasesTitle: 'அவசர வாக்குகள்',
  },
  te: {
    translateLanguageTitle: 'భాషను అనువదించండి',
    selectedLanguage: 'ఎంచుకోబడిన భాష:',
    enterTextPlaceholder: 'అనువదించడానికి టెక్స్ట్ ఎంటర్ చేయండి',
    translatedText: 'అనువదించబడిన టెక్స్ట్',
    translateButton: 'అనువదించండి',
    selectLang: 'భాషను ఎంచుకోండి',
    selectTargetLang: 'లక్షిత భాషను ఎంచుకోండి',
    matchingGameTitle: 'సరిచేసే ఆట',
    exitTitle: 'నిష్క్రమించు',
    wordBookTitle: 'పదపుస్తకం',
    translationTitle: 'అనువాదం',
    commonPhrasesTitle: 'సామాన్య వాక్యం',
    congratulationTitle: 'అభినందనలు!',
    congratulationTitle2: 'మీరు అన్ని జోడులను పరిష్కరించారు!',
    okTitle: 'అలాగే',
    travelPhrasesTitle: 'ప్రయాణ పదాలు',
    emergencyPhrasesTitle: 'అత్యవసర పదాలు',
  },
  th: {
    translateLanguageTitle: 'แปลภาษา',
    selectedLanguage: 'ภาษาที่เลือก:',
    enterTextPlaceholder: 'ป้อนข้อความเพื่อแปล',
    translatedText: 'ข้อความที่แปล',
    translateButton: 'แปล',
    selectLang: 'เลือกภาษา',
    selectTargetLang: 'เลือกภาษาเป้าหมาย',
    matchingGameTitle: 'เกมจับคู่',
    exitTitle: 'ออก',
    wordBookTitle: 'หนังสือคำศัพท์',
    translationTitle: 'การแปล',
    commonPhrasesTitle: 'วลีทั่วไป',
    congratulationTitle: 'ขอแสดงความยินดี!',
    congratulationTitle2: 'คุณจับคู่ทั้งหมดแล้ว!',
    okTitle: 'ตกลง',
    travelPhrasesTitle: 'วลีการเดินทาง',
    emergencyPhrasesTitle: 'วลีฉุกเฉิน',
  },
  tr: {
    translateLanguageTitle: 'Dil Çevir',
    selectedLanguage: 'Seçilen Dil:',
    enterTextPlaceholder: 'Çevirmek için metin girin',
    translatedText: 'Çevrilen Metin',
    translateButton: 'Dil Çevir',
    selectLang: 'Dil Seç',
    selectTargetLang: 'Hedef Dil Seç',
    matchingGameTitle: 'Eşleştirme Oyunu',
    exitTitle: 'Çıkış',
    wordBookTitle: 'Kelime Kitabı',
    translationTitle: 'Çeviri',
    commonPhrasesTitle: 'Ortak İfade',
    congratulationTitle: 'Tebrikler!',
    congratulationTitle2: 'Tüm çiftleri eşleştirdiniz!',
    okTitle: 'Tamam',
    travelPhrasesTitle: 'Seyahat İfadesi',
    emergencyPhrasesTitle: 'Acil Durum İfadesi',
  },
  vi: {
    translateLanguageTitle: 'Dịch Ngôn Ngữ',
    selectedLanguage: 'Ngôn ngữ đã chọn:',
    enterTextPlaceholder: 'Nhập văn bản để dịch',
    translatedText: 'Văn bản đã dịch',
    translateButton: 'Dịch Ngôn Ngữ',
    selectLang: 'Chọn Ngôn Ngữ',
    selectTargetLang: 'Chọn Ngôn Ngữ Mục Tiêu',
    matchingGameTitle: 'Trò chơi kết hợp',
    exitTitle: 'Thoát',
    wordBookTitle: 'Sách Từ Vựng',
    translationTitle: 'Dịch',
    commonPhrasesTitle: 'Cụm Từ Phổ Biến',
    congratulationTitle: 'Chúc mừng!',
    congratulationTitle2: 'Bạn đã ghép đôi tất cả!',
    okTitle: 'Đồng ý',
    travelPhrasesTitle: 'Câu Hỏi Du Lịch',
    emergencyPhrasesTitle: 'Câu Hỏi Khẩn Cấp',
  },
};

const LanguageContext = createContext();

export const useLanguageContext = () => {
  return useContext(LanguageContext);
};

export const LanguageProvider = ({ children }) => {
  const [selectedLanguage, setSelectedLanguage] = useState('English'); // Initialize with the default language

  const setLanguage = (language) => {
    setSelectedLanguage(language);
  };

  return (
    <LanguageContext.Provider
      value={{ selectedLanguage, setLanguage, translations }}>
      {children}
    </LanguageContext.Provider>
  );
};
